// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jslt.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.schibsted.spt.data.jslt.*;
import com.fasterxml.jackson.databind.*;

public class JSLT extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Input;
	private java.lang.String Expression;

	public JSLT(IContext context, java.lang.String Input, java.lang.String Expression)
	{
		super(context);
		this.Input = Input;
		this.Expression = Expression;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
	    ObjectMapper mapper = new ObjectMapper();
	    JsonNode input = mapper.readTree(Input);
		Expression jslt = Parser.compileString(Expression);
		JsonNode output = jslt.apply(input);
		java.lang.String outputString = output.toPrettyString(); 
		return outputString;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JSLT";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
