// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_Transform(IContext context, myfirstmodule.proxies.JSLTDemo _jSLTDemo)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JSLTDemo", _jSLTDemo == null ? null : _jSLTDemo.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Transform").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.JSLTDemo dS_NewDemo(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_NewDemo").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.JSLTDemo.initialize(context, result);
	}
}