// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jslt.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the JSLT module
	public static java.lang.String arrayPush(IContext context, java.lang.String _element, java.lang.String _array)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element);
		params.put("Array", _array);
		return (java.lang.String) Core.microflowCall("JSLT.ArrayPush").withParams(params).execute(context);
	}
	public static java.lang.String arrayUnshift(IContext context, java.lang.String _element, java.lang.String _array)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Element", _element);
		params.put("Array", _array);
		return (java.lang.String) Core.microflowCall("JSLT.ArrayUnshift").withParams(params).execute(context);
	}
}