// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class JSLTDemo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jSLTDemoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.JSLTDemo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Input("Input"),
		Expression("Expression"),
		Output("Output"),
		WithObjectFilter("WithObjectFilter"),
		Filter("Filter");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JSLTDemo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.JSLTDemo"));
	}

	protected JSLTDemo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jSLTDemoMendixObject)
	{
		if (jSLTDemoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.JSLTDemo", jSLTDemoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.JSLTDemo");

		this.jSLTDemoMendixObject = jSLTDemoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JSLTDemo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.JSLTDemo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.JSLTDemo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.JSLTDemo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.JSLTDemo(context, mendixObject);
	}

	public static myfirstmodule.proxies.JSLTDemo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.JSLTDemo.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Input
	 */
	public final java.lang.String getInput()
	{
		return getInput(getContext());
	}

	/**
	 * @param context
	 * @return value of Input
	 */
	public final java.lang.String getInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Input.toString());
	}

	/**
	 * Set value of Input
	 * @param input
	 */
	public final void setInput(java.lang.String input)
	{
		setInput(getContext(), input);
	}

	/**
	 * Set value of Input
	 * @param context
	 * @param input
	 */
	public final void setInput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String input)
	{
		getMendixObject().setValue(context, MemberNames.Input.toString(), input);
	}

	/**
	 * @return value of Expression
	 */
	public final java.lang.String getExpression()
	{
		return getExpression(getContext());
	}

	/**
	 * @param context
	 * @return value of Expression
	 */
	public final java.lang.String getExpression(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Expression.toString());
	}

	/**
	 * Set value of Expression
	 * @param expression
	 */
	public final void setExpression(java.lang.String expression)
	{
		setExpression(getContext(), expression);
	}

	/**
	 * Set value of Expression
	 * @param context
	 * @param expression
	 */
	public final void setExpression(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expression)
	{
		getMendixObject().setValue(context, MemberNames.Expression.toString(), expression);
	}

	/**
	 * @return value of Output
	 */
	public final java.lang.String getOutput()
	{
		return getOutput(getContext());
	}

	/**
	 * @param context
	 * @return value of Output
	 */
	public final java.lang.String getOutput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Output.toString());
	}

	/**
	 * Set value of Output
	 * @param output
	 */
	public final void setOutput(java.lang.String output)
	{
		setOutput(getContext(), output);
	}

	/**
	 * Set value of Output
	 * @param context
	 * @param output
	 */
	public final void setOutput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String output)
	{
		getMendixObject().setValue(context, MemberNames.Output.toString(), output);
	}

	/**
	 * @return value of WithObjectFilter
	 */
	public final java.lang.Boolean getWithObjectFilter()
	{
		return getWithObjectFilter(getContext());
	}

	/**
	 * @param context
	 * @return value of WithObjectFilter
	 */
	public final java.lang.Boolean getWithObjectFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WithObjectFilter.toString());
	}

	/**
	 * Set value of WithObjectFilter
	 * @param withobjectfilter
	 */
	public final void setWithObjectFilter(java.lang.Boolean withobjectfilter)
	{
		setWithObjectFilter(getContext(), withobjectfilter);
	}

	/**
	 * Set value of WithObjectFilter
	 * @param context
	 * @param withobjectfilter
	 */
	public final void setWithObjectFilter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean withobjectfilter)
	{
		getMendixObject().setValue(context, MemberNames.WithObjectFilter.toString(), withobjectfilter);
	}

	/**
	 * @return value of Filter
	 */
	public final java.lang.String getFilter()
	{
		return getFilter(getContext());
	}

	/**
	 * @param context
	 * @return value of Filter
	 */
	public final java.lang.String getFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Filter.toString());
	}

	/**
	 * Set value of Filter
	 * @param filter
	 */
	public final void setFilter(java.lang.String filter)
	{
		setFilter(getContext(), filter);
	}

	/**
	 * Set value of Filter
	 * @param context
	 * @param filter
	 */
	public final void setFilter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filter)
	{
		getMendixObject().setValue(context, MemberNames.Filter.toString(), filter);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jSLTDemoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.JSLTDemo that = (myfirstmodule.proxies.JSLTDemo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.JSLTDemo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
